/**
 *
 * We are given two strings s and t. String t is generated by random shuffling
 * string s and then add one more letter at a random position. Return the letter
 * that was added to t. Using the logic of XOR we know that if we xor all the values
 * of s, then xor all the values of t, the value remaining will be missing char.
 *
 */

#include <stdio.h>

char findTheDifference(char *s, char *t)
{
    char added = 0;

    while (*s)
    {
        added ^= *s;
        s++;
    }

    while (*t)
    {
        added ^= *t;
        t++;
    }

    return added;
}

int main()
{
    char s[] = "abcd";
    char t[] = "abcde";

    char result = findTheDifference(s, t);
    printf("Added character: %c\n", result);

    return 0;
}

/**
 *
 * Time complexity is O(n)
 * Space complexity is O(1)
 *
 */